server:
  port: 8081

spring:
  application:
    name: product
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: bmn
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
