server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://USER
          predicates:
            - Path=/api/v1/auth/**
        - id: user
          uri: lb://USER
          predicates:
            - Path=/api/v1/user/**
        - id: product
          uri: lb://PRODUCT
          predicates:
            - Path=/api/v1/product/**
        - id: order
          uri: lb://ORDER
          predicates:
            - Path=/api/v1/order/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

